package dev.cacnio.RevECom.entity;

import jakarta.persistence.*;

import java.util.Objects;


/*
 * This class models an item in our eShop
 */
@Entity
@Table(name="product")
public class Product {
    /*
     * TODO: Fields
     *  id (autogenerate?)
     *  name
     *  image (path?)
     *  price
     *  description
     *  keywords/categories (stretch)
     *  user reviews (stretch goal?)
     * 
     * TODO: Methods
     *  Constructor
     *  Getters
     *  Setters
     *  equals override
     *  toString override
     */
    @Column (name="item_id")
    @Id @GeneratedValue
    private Integer item_id;

    @Column (name="name")
    private String name;

    @Column (name="image_path")
    private String image_path;

    @Column (name="price")
    private Double price;

    @Column (name="description")
    private String description;

    @Column (name="category")
    private String category;

    public Product(){}

    //constructor for new items (id autogenerated)
    public Product(String name, String image_path, Double price, String description, String category){
        this.name = name;
        this.image_path = image_path;
        this.price = price;
        this.description = description;
        this.category = category;
    }

    //constructor for retrieved items
    public Product(Integer item_id, String name, String image_path, Double price, String description, String category){
        this.item_id = item_id;
        this.name = name;
        this.image_path = image_path;
        this.price = price;
        this.description = description;
        this.category = category;
    }

    //accessor methods
    public Integer getItem_id() {
        return item_id;
    }
    public String getName(){
        return name;
    }
    public String getImage_path(){
        return image_path;
    }
    public Double getPrice(){
        return price;
    }
    public String getDescription(){
        return description;
    }
    public String getCategory(){
        return category;
    }

    //mutator methods
    public void setItem_id(Integer item_id){
        this.item_id = item_id;
    }
    public void setName(String name) {
        this.name = name;
    }
    public void setImage_path(String image_path) {
        this.image_path = image_path;
    }
    public void setPrice(Double price) {
        this.price = price;
    }
    public void setDescription(String description) {
        this.description = description;
    }
    public void setCategory(String category) {
        this.category = category;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Product product = (Product) o;
        return Objects.equals(item_id, product.item_id) && Objects.equals(name, product.name) && Objects.equals(image_path, product.image_path) && Objects.equals(price, product.price) && Objects.equals(description, product.description) && Objects.equals(category, product.category);
    }

    @Override
    public int hashCode() {
        return Objects.hash(item_id, name, image_path, price, description, category);
    }

    @Override
    public String toString() {
        return "Product{"+
                "item_id="+ item_id +
                ", name="+ name +
                ", image_path="+ image_path +
                ", price="+ price +
                ", description="+ description +
                ", category=" + category + "}";
    }
}
